export declare enum BC_CMD_E {
    E_BC_CMD_GET_OSD = 2001,
    E_BC_CMD_SET_OSD = 2002,
    E_BC_CMD_GET_COLOR = 2003,
    E_BC_CMD_SET_COLOR = 2004,
    E_BC_CMD_GET_VILOST = 2005,
    E_BC_CMD_SET_VILOST = 2006,
    E_BC_CMD_GET_MOTION = 2007,
    E_BC_CMD_SET_MOTION = 2008,
    E_BC_CMD_GET_BLIND = 2009,
    E_BC_CMD_SET_BLIND = 2010,
    E_BC_CMD_GET_COVER = 2011,
    E_BC_CMD_SET_COVER = 2012,
    E_BC_CMD_GET_CAMERA = 2013,
    E_BC_CMD_SET_CAMERA = 2014,
    E_BC_CMD_GET_DST = 2015,
    E_BC_CMD_SET_DST = 2016,
    E_BC_CMD_GET_EMAIL = 2017,
    E_BC_CMD_SET_EMAIL = 2018,
    E_BC_CMD_GET_COMPRESS = 2019,
    E_BC_CMD_SET_COMPRESS = 2020,
    E_BC_CMD_GET_SYS = 2021,
    E_BC_CMD_SET_SYS = 2022,
    E_BC_CMD_GET_VERSION = 2023,
    E_BC_CMD_GET_ENC_PROFILE = 2024,
    E_BC_CMD_GET_OUTPUT = 2025,
    E_BC_CMD_SET_OUTPUT = 2026,
    E_BC_CMD_GET_ADVRECORD = 2027,
    E_BC_CMD_SET_ADVRECORD = 2028,
    E_BC_CMD_GET_RECORDSCHED = 2029,
    E_BC_CMD_SET_RECORDSCHED = 2030,
    E_BC_CMD_GET_LINKTYPE = 2033,
    E_BC_CMD_SET_LINKTYPE = 2034,
    E_BC_CMD_GET_PPPOECFG = 2035,
    E_BC_CMD_SET_PPPOECFG = 2036,
    E_BC_CMD_GET_LOCAL = 2037,
    E_BC_CMD_SET_LOCAL = 2038,
    E_BC_CMD_GET_UPNPSTATE = 2039,
    E_BC_CMD_SET_UPNPSTATE = 2040,
    E_BC_CMD_GET_NORMAL_PORT = 2041,
    E_BC_CMD_SET_NORMAL_PORT = 2042,
    E_BC_CMD_GET_NTPCFG = 2043,
    E_BC_CMD_SET_NTPCFG = 2044,
    E_BC_CMD_GET_DDNSCFG = 2045,
    E_BC_CMD_SET_DDNSCFG = 2046,
    E_BC_CMD_GET_IPFILTER = 2047,
    E_BC_CMD_SET_IPFILTER = 2048,
    E_BC_CMD_GET_HDDFULL_EXPCFG = 2049,
    E_BC_CMD_SET_HDDFULL_EXPCFG = 2050,
    E_BC_CMD_GET_HDDERR_EXPCFG = 2051,
    E_BC_CMD_SET_HDDERR_EXPCFG = 2052,
    E_BC_CMD_GET_NETDISCONNECT_EXPCFG = 2053,
    E_BC_CMD_SET_NETDISCONNECT_EXPCFG = 2054,
    E_BC_CMD_GET_IPCONFLICT_EXPCFG = 2055,
    E_BC_CMD_SET_IPCONFLICT_EXPCFG = 2056,
    E_BC_CMD_GET_PTZCFG = 2057,
    E_BC_CMD_SET_PTZCFG = 2058,
    E_BC_CMD_INIT_HDD = 2059,
    E_BC_CMD_GET_HDD_CFG = 2060,
    E_BC_CMD_GET_AUTOREBOOT_CFG = 2061,
    E_BC_CMD_SET_AUTOREBOOT_CFG = 2062,
    E_BC_CMD_GET_PERFORMANCE = 2063,
    E_BC_CMD_GET_FTPCFG = 2064,
    E_BC_CMD_SET_FTPCFG = 2065,
    E_BC_CMD_GET_FTPTASK = 2066,
    E_BC_CMD_SET_FTPTASK = 2067,
    E_BC_CMD_GET_USERCFG = 2068,
    E_BC_CMD_SET_USERCFG = 2069,
    E_BC_CMD_GET_USER_ONLINE = 2070,
    E_BC_CMD_SET_USER_ONLINE = 2071,
    E_BC_CMD_REPLAY_SEEK_TIME = 2072,
    E_BC_CMD_GET_WIFI_INFO = 2073,
    E_BC_CMD_SET_WIFI_INFO = 2074,
    E_BC_CMD_GET_ALARMINCFG = 2075,
    E_BC_CMD_SET_ALARMINCFG = 2076,
    E_BC_CMD_GET_ALARMOUTCFG = 2077,
    E_BC_CMD_SET_ALARMOUTCFG = 2078,
    E_BC_CMD_GET_BOOTPWD_STATE = 2079,
    E_BC_CMD_SET_BOOTPWD_STATE = 2080,
    E_BC_CMD_GET_VTALARMIN = 2081,
    E_BC_CMD_SET_VTALARMIN = 2082,
    E_BC_CMD_GET_FDALARMIN = 2083,
    E_BC_CMD_SET_FDALARMIN = 2084,
    E_BC_CMD_GET_IDALARMIN = 2085,
    E_BC_CMD_SET_IDALARMIN = 2086,
    E_BC_CMD_LOGIN = 2087,
    E_BC_CMD_LOGOUT = 2088,
    E_BC_CMD_REALPLAY = 2089,
    E_BC_CMD_STOPREALPLAY = 2090,
    E_BC_CMD_UPGRADE = 2091,
    E_BC_CMD_PLAYBACKBYNAME = 2092,
    E_BC_CMD_STOPPLAYBACKBYNAME = 2093,
    E_BC_CMD_PLAYBACKBYTIME = 2094,
    E_BC_CMD_STOPPLAYBACKBYTIME = 2095,
    E_BC_CMD_DOWNLOAD = 2096,
    E_BC_CMD_DOWNLOAD_STOP = 2097,
    E_BC_CMD_GETLOG = 2098,
    E_BC_CMD_EXPORT = 2099,
    E_BC_CMD_IMPORT = 2100,
    E_BC_CMD_REBOOT = 2101,
    E_BC_CMD_GET_RECFILEDATE = 2102,
    E_BC_CMD_RESTORE = 2103,
    E_BC_CMD_EMAILTEST = 2104,
    E_BC_CMD_SHUTDOWN = 2105,
    E_BC_CMD_GET_MANALARM = 2106,
    E_BC_CMD_SET_MANALARM = 2107,
    E_BC_CMD_PTZ_CONTROL = 2108,
    E_BC_CMD_PUSH_ADD = 2109,
    E_BC_CMD_PUSH_DEL = 2110,
    E_BC_CMD_GET_RFSENSOR = 2111,
    E_BC_CMD_SET_RFSENSOR = 2112,
    E_BC_CMD_SEARCH_RECFILES = 2113,
    E_BC_CMD_CONNECTION_TEST = 2114,
    E_BC_CMD_RECONNECT = 2115,
    E_BC_CMD_GET_ABILITY = 2116,
    E_BC_CMD_IFRAME_PREVIEW = 2117,
    E_BC_CMD_IFRAME_REPLAY = 2118,
    E_BC_CMD_CAMERA_STATE = 2119,
    E_BC_CMD_GET_ADVANCED_PORTS = 2120,
    E_BC_CMD_SET_ADVANCED_PORTS = 2121,
    E_BC_CMD_GET_UID = 2122,
    E_BC_CMD_ONLINE_UPDATE = 2123,
    E_BC_CMD_FORCE_PASSWORD = 2124,
    E_BC_CMD_SET_ABILITY = 2125,
    E_BC_CMD_GET_PRESET = 2126,
    E_BC_CMD_SET_PRESET = 2127,
    E_BC_CMD_GET_CRUISE = 2128,
    E_BC_CMD_SET_CRUISE = 2129,
    E_BC_CMD_GET_DEFAULT_CAMERA = 2130,
    E_BC_CMD_UPGRADE_PROGRESS = 2131,
    E_BC_CMD_WIFI_TEST = 2133,
    E_BC_CMD_FTP_TEST = 2134,
    E_BC_CMD_GET_SCAN_AP = 2135,
    E_BC_CMD_EXPORT_PROGRESS = 2136,
    E_BC_CMD_IMPORT_PROGRESS = 2137,
    E_BC_CMD_LOCAL_RECORD = 2138,
    E_BC_CMD_STOP_LOCAL_RECORD = 2139,
    E_BC_CMD_CONFIG_LIVE = 2140,
    E_BC_CMD_STOP_CONFIG_LIVE = 2141,
    E_BC_CMD_START_ALARM_REPORT = 2142,
    E_BC_CMD_STOP_ALARM_REPORT = 2143,
    E_BC_CMD_ALARM_REPORT = 2144,
    E_BC_CMD_DOWNLOAD_CUT = 2145,
    E_BC_CMD_DOWNLOAD_CUT_STOP = 2146,
    E_BC_CMD_DOWNLOAD_PROGRESS = 2147,
    E_BC_CMD_DOWNLOAD_CUT_PROGRESS = 2148,
    E_BC_CMD_GET_CAMERA_CFG = 2149,
    E_BC_CMD_SET_CAMERA_CFG = 2150,
    E_BC_CMD_GET_LED_STATE = 2151,
    E_BC_CMD_SET_LED_STATE = 2152,
    E_BC_CMD_GET_PTOP_CFG = 2153,
    E_BC_CMD_SET_PTOP_CFG = 2154,
    E_BC_CMD_TALK_OPEN = 2155,
    E_BC_CMD_TALK_CLOSE = 2156,
    E_BC_CMD_GET_TALK_ABILITY = 2157,
    E_BC_CMD_TALK_FDX_STREAM = 2158,
    E_BC_CMD_SNAP = 2159,
    E_BC_CMD_GOTO_PRESET = 2160,
    E_BC_CMD_SET_USER_ALL_ABILITY = 2161,
    E_BC_CMD_GET_WIFI_SIGNAL = 2162,
    E_BC_CMD_GET_AUTO_UPDATE = 2163,
    E_BC_CMD_SET_AUTO_UPDATE = 2164,
    E_BC_CMD_GET_ONLINE_NEW_FIRMWARE = 2165,
    E_BC_CMD_RTMP_START = 2166,
    E_BC_CMD_RTMP_STOP = 2167,
    E_BC_CMD_GET_EMAIL_TASK = 2168,
    E_BC_CMD_SET_EMAIL_TASK = 2169,
    E_BC_CMD_GET_PUSH_TASK = 2170,
    E_BC_CMD_SET_PUSH_TASK = 2171,
    E_BC_CMD_GET_RF_CFG = 2172,
    E_BC_CMD_SET_RF_CFG = 2173,
    E_BC_CMD_GET_BATTERY_ELECTRICITY = 2174,
    E_BC_CMD_SET_RF_ALARM_STATUS = 2175,
    E_BC_CMD_GET_ONLINE_UPDATE_STATUS = 2176,
    E_BC_CMD_GET_AUTO_FOCUS = 2177,
    E_BC_CMD_SET_AUTO_FOCUS = 2178,
    E_BC_CMD_GET_CROP_CFG = 2179,
    E_BC_CMD_SET_CROP_CFG = 2180,
    E_BC_CMD_CROP_SNAP = 2181,
    E_BC_CMD_DEVICE_SLEEP = 2182,
    E_BC_CMD_GET_AUDIO_TASK = 2183,
    E_BC_CMD_SET_AUDIO_TASK = 2184,
    E_BC_CMD_BATTERY_HEARTBEAT_RSP = 2185,
    E_BC_CMD_GET_AP_MODE_INFO = 2191,
    E_BC_CMD_REPORT_DEVICE_EXCEPTION = 2192,
    E_BC_CMD_BASE_REPORT_ONLINE_DEVICE = 2193,
    E_BC_CMD_BASE_DELETE_ONLINE_DEVICE = 2194,
    E_BC_CMD_BASE_GET_RF_CFG = 2195,
    E_BC_CMD_BASE_SET_RF_CFG = 2196,
    E_BC_CMD_BASE_GET_WIFI_QRCODE = 2197,
    E_BC_CMD_BASE_RESPONSE_LIVE_TIME = 2198,
    E_BC_CMD_BASE_SET_RF_ALARM_STATUS = 2199,
    E_BC_CMD_REPORT_BATTERY_INFO_LIST = 2200,
    E_BC_CMD_GET_BATTERY_INFO = 2201,
    E_BC_CMD_SET_DEVICE_NAME = 2202,
    E_BC_CMD_SET_ISP_DAY_NIGHT_MODE = 2203,
    E_BC_CMD_BASE_SET_WIFI_QRCODE = 2204,
    E_BC_CMD_GET_3G_4G_INFO = 2205,
    E_BC_CMD_REPORT_3G_4G_INFO = 2206,
    E_BC_CMD_GET_SIM_MODULE_INFO = 2207,
    E_BC_CMD_SET_SIM_MODULE_INFO = 2208,
    E_BC_CMD_GET_BATTERY_ANALYSIS = 2209,
    E_BC_CMD_GET_CLOUD_INFO = 2210,
    E_BC_CMD_BIND_CLOUD = 2211,
    E_BC_CMD_GET_CLOUD_CFG = 2212,
    E_BC_CMD_SET_CLOUD_CFG = 2213,
    E_BC_CMD_GET_RINGTONE_FILE_INFO = 2214,
    E_BC_CMD_IMPORT_RINGTONE = 2215,
    E_BC_CMD_IMPORT_RINGTONE_PROGRESS = 2216,
    E_BC_CMD_SAVE_RINGTONE = 2217,
    E_BC_CMD_MANUAL_RING_DOWN = 2218,
    E_BC_CMD_GET_RINGTONE_CFG = 2219,
    E_BC_CMD_SET_RINGTONE_CFG = 2220,
    E_BC_CMD_MUTE_ALARM_AUDIO = 2221,
    E_BC_CMD_GET_RINGTONE_ABILITY = 2222,
    E_BC_CMD_SEARCH_ALARM_VIDEOS = 2223,
    E_BC_CMD_NAS_BIND = 2224,
    E_BC_CMD_NAS_UNBIND = 2225,
    E_BC_CMD_NAS_GET_BIND_INFO = 2226,
    E_BC_CMD_GET_SIGNATURE_LOGIN_CFG = 2227,
    E_BC_CMD_SET_SIGNATURE_LOGIN_CFG = 2228,
    E_BC_CMD_SYNC_UTC_TIME = 2229,
    E_BC_CMD_WITHOUT_INTERATION_REPORT = 2230,
    E_BC_CMD_CONNECTION_STATE_CHANGE = 3001,
    E_BC_CMD_LOGIN_INFO_CHANGE = 3002,
    E_BC_CMD_BUTT = -1
}
export declare enum BC_RSP_CODE_E {
    E_BC_RSP_OK = 0,
    E_BC_RSP_NOT_INIT = 1,
    E_BC_RSP_HOST_ERR = 2,
    E_BC_RSP_USER_LIMIT = 3,
    E_BC_RSP_USER_NOT_EXIST = 4,
    E_BC_RSP_TIMEOUT = 5,
    E_BC_RSP_SEND_ERR = 6,
    E_BC_RSP_SESSION_LIMIT = 7,
    E_BC_RSP_MALLOC_FAILED = 8,
    E_BC_RSP_CREATE_THREAD_FAILED = 9,
    E_BC_RSP_AUTH_FAILED = 10,
    E_BC_RSP_INVALID_SESSIONID = 11,
    E_BC_RSP_INVALID_HANDLE = 12,
    E_BC_RSP_INVALID_CHNID = 13,
    E_BC_RSP_INVALID_USERID = 14,
    E_BC_RSP_MISS_PARA = 15,
    E_BC_RSP_FILE_CHECK_ERR = 16,
    E_BC_RSP_FILE_ACCESS_ERR = 17,
    E_BC_RSP_SYS_BUSY = 18,
    E_BC_RSP_SDK_ERR = 19,
    E_BC_RSP_PARA_IS_NULL = 20,
    E_BC_RSP_CONNECT_FAILED = 21,
    E_BC_RSP_OLD_VERSION = 1001,
    E_BC_RSP_WRITE_FAILED = 1002,
    E_BC_RSP_NOT_EXIST = 1003,
    E_BC_RSP_TEMPORARILY_UNAVAILABLE = 1004,
    E_BC_RSP_FILE_NOFIND = 1005,
    E_BC_RSP_FILE_NOMOREFILE = 1006,
    E_BC_RSP_FILE_EXCEPTION = 1007,
    E_BC_RSP_CMD_NOT_SUPPORT = 1008,
    E_BC_RSP_CMD_UPGRADE_SAME_VER = 2001,
    E_BC_RSP_CMD_UPGRADE_CHECK_FAILED = 2002,
    E_BC_RSP_CMD_UPGRADE_BUSY = 2003,
    E_BC_RSP_CMD_UPGRADE_OOM = 2004,
    E_BC_RSP_CMD_FTP_TEST_UNKNOWN_FAILED = 4001,
    E_BC_RSP_CMD_FTP_TEST_LOGIN_FAILED = 4002,
    E_BC_RSP_CMD_FTP_TEST_CREATE_FAILED = 4003,
    E_BC_RSP_CMD_FTP_TEST_UPLOAD_FAILED = 4004,
    E_BC_RSP_INVALID = -1
}
export declare enum BCSDK_DEVICE_STATE_E {
    BCSDK_DEVICE_STATE_NOTREADY = 0,
    BCSDK_DEVICE_STATE_OPENING = 1,
    BCSDK_DEVICE_STATE_OPENSUCCESS = 2,
    BCSDK_DEVICE_STATE_OPENFAILED = 3,
    BCSDK_DEVICE_STATE_OPENTIMEOUT = 4,
    BCSDK_DEVICE_STATE_NOTONLINE = 5,
    BCSDK_DEVICE_STATE_PASSWORDERROR = 6,
    BCSDK_DEVICE_STATE_CLOSING = 7,
    BCSDK_DEVICE_STATE_CLOSED = 8,
    BCSDK_DEVICE_STATE_ABANDON = 9
}
export declare enum BC_YUV_FORMAT_E {
    /**
    * I420: YYYYYYYY UU VV     =>YUV420P
    * YV12: YYYYYYYY VV UU     =>YUV420P
    * NV12: YYYYYYYY UVUV      =>YUV420SP
    * NV21: YYYYYYYY VUVU      =>YUV420SP
    */
    BC_YUV_FORMAT_I420 = 0,
    BC_YUV_FORMAT_YV12 = 1,
    BC_YUV_FORMAT_NV12 = 2,
    BC_YUV_FORMAT_NV21 = 3
}
export declare enum BC_MEDIA_TYPE_E {
    BC_MEDIA_TYPE_LIVE = 0,
    BC_MEDIA_TYPE_PLAYBACK = 1,
    BC_MEDIA_TYPE_UNKNOW = 255
}
export declare enum BC_STREAM_TYPE_E {
    E_BC_STREAM_MAIN = 0,
    E_BC_STREAM_SUB = 1,
    E_BC_STREAM_MOBILE = 2,
    E_BC_STREAM_EXTERN = 4,
    E_BC_STREAM_BUTT = 5
}
export declare enum BC_DEVICE_TYPE_E {
    E_BC_DEVICE_TYPE_DVR = 1,
    E_BC_DEVICE_TYPE_IPC = 2,
    E_BC_DEVICE_TYPE_NVR = 3,
    E_BC_DEVICE_TYPE_WIFI_IPC = 4,
    E_BC_DEVICE_TYPE_WIFI_NVR = 5,
    E_BC_DEVICE_TYPE_NXP_IPC = 6,
    E_BC_DEVICE_TYPE_WIFI_SOLO_IPC = 7,
    E_BC_DEVICE_TYPE_BASE = 8,
    E_BC_DEVICE_TYPE_UNKNOW = 126,
    E_BC_DEVICE_TYPE_BUTT = 127
}
export declare enum BC_DEVICE_NORM_E {
    BC_DEVICE_NORM_UNKNOW = -1,
    BC_DEVICE_NORM_PAL = 0,
    BC_DEVICE_NORM_NTSC = 1
}
export declare enum BC_SONG_P2P_TYPE_E {
    BC_SONG_P2P_TYPE_UNKNOW = -1,
    BC_SONG_P2P_TYPE_NONE = 0,
    BC_SONG_P2P_TYPE_KEEN = 1,
    BC_SONG_P2P_TYPE_CARD = 2,
    BC_SONG_P2P_TYPE_BASE = 3,
    BC_SONG_P2P_TYPE_ARGUS_2 = 4,
    BC_SONG_P2P_TYPE_GO = 5,
    BC_SONG_P2P_TYPE_ARGUS_PRO = 6,
    BC_SONG_P2P_TYPE_KEEN_2 = 7,
    BC_SONG_P2P_TYPE_B16 = 8,
    BC_SONG_P2P_TYPE_OTHERS = 255
}
export declare enum BCSDK_DEVICE_RF_STATE_E {
    BCSDK_DEVICE_RF_STATE_UNKNOW = 0,
    BCSDK_DEVICE_RF_STATE_INHOME = 1,
    BCSDK_DEVICE_RF_STATE_OUTHOME = 2,
    BCSDK_DEVICE_RF_STATE_SLEEP = 3,
    BCSDK_DEVICE_RF_STATE_DISARM = 4
}
export declare enum BC_ONLINE_UPDATE_STATUS_E {
    BC_ONLINE_UPDATE_STATUS_NONE = 0,
    BC_ONLINE_UPDATE_STATUS_NEED_UPDATE = 1,
    BC_ONLINE_UPDATE_STATUS_WAIT_DOWNLOAD = 2,
    BC_ONLINE_UPDATE_STATUS_DOWNLOADING = 3,
    BC_ONLINE_UPDATE_STATUS_UPDATING = 4,
    BC_ONLINE_UPDATE_STATUS_STOPPED = 5,
    BC_ONLINE_UPDATE_STATUS_TIMEOUT = 6,
    BC_ONLINE_UPDATE_STATUS_FINISHED = 7,
    BC_ONLINE_UPDATE_STATUS_UPDATE_FAILED = 8,
    BC_ONLINE_UPDATE_STATUS_IMG_ERROR = 9
}
export declare enum BCSDK_NET_TYPE_E {
    BCSDK_NET_TYPE_NONE = 0,
    BCSDK_NET_TYPE_ETHER = 1,
    BCSDK_NET_TYPE_WIFI = 2,
    BCSDK_NET_TYPE_3G4G = 3
}
export declare enum RECORD_TYPE_E {
    RECORD_TYPE_SCHEDULE = 1,
    RECORD_TYPE_MANUAL = 2,
    RECORD_TYPE_ALARM = 4,
    RECORD_TYPE_ALL = 7
}
export declare enum BC_FILE_TYPE_E {
    BC_FILE_TYPE_H264 = 0,
    BC_FILE_TYPE_MP4 = 1,
    BC_FILE_TYPE_FLV = 2
}
export declare enum BCSDK_MEDIA_STATE_E {
    BCSDK_MEDIA_STATE_NONE = 0,
    BCSDK_MEDIA_STATE_OPENED = 1,
    BCSDK_MEDIA_STATE_STARTED = 2,
    BCSDK_MEDIA_STATE_PAUSED = 3,
    BCSDK_MEDIA_STATE_CLOSED = 4
}
export declare enum BCSDK_CONFIG_STATE_E {
    BCSDK_CONFIG_STATE_NOTREADY = 0,
    BCSDK_CONFIG_STATE_WAITING = 1,
    BCSDK_CONFIG_STATE_SUCCESS = 2,
    BCSDK_CONFIG_STATE_FAILED = 3,
    BCSDK_CONFIG_STATE_TIMEOUT = 4
}
export declare enum BC_TVSYSTEM_E {
    E_BC_TS_PAL = 0,
    E_BC_TS_NTSC = 1,
    E_BC_TS_INVALID = 2
}
export declare enum BC_DATE_TYPE_E {
    E_BC_OSD_MDY = 0,
    E_BC_OSD_YMD = 1,
    E_BC_OSD_DMY = 2
}
export declare enum BC_TIME_FMT_E {
    OSD_TIME_24 = 0,
    OSD_TIME_12 = 1,
    OSD_TIME_BUTT = 2
}
export declare enum BC_REBOOT_AT_E {
    E_BC_RA_EVERY_DAY = 0,
    E_BC_RA_EVERY_SUNDAY = 1,
    E_BC_RA_EVERY_MONDAY = 2,
    E_BC_RA_EVERY_TUESDAY = 3,
    E_BC_RA_EVERY_WEDNESDAY = 4,
    E_BC_RA_EVERY_THURSDAY = 5,
    E_BC_RA_EVERY_FRIDAY = 6,
    E_BC_RA_EVERY_SATURDAY = 7
}
export declare enum BC_RESOLUTION_E {
    E_BC_RESO_D1 = 0,
    E_BC_RESO_HD1 = 1,
    E_BC_RESO_2CIF = 2,
    E_BC_RESO_CIF = 3,
    E_BC_RESO_QCIF = 4,
    E_BC_RESO_1024_768 = 5,
    E_BC_RESO_1280_720 = 6,
    E_BC_RESO_1280_800 = 7,
    E_BC_RESO_1280_1024 = 8,
    E_BC_RESO_1366_768 = 9,
    E_BC_RESO_1400_1050 = 10,
    E_BC_RESO_1440_900 = 11,
    E_BC_RESO_1600_900 = 12,
    E_BC_RESO_1600_1200 = 13,
    E_BC_RESO_1680_1050 = 14,
    E_BC_RESO_1920_1080 = 15,
    E_BC_RESO_1920_1200 = 16,
    E_BC_RESO_2048_1152 = 17,
    E_BC_RESO_960P = 18,
    E_BC_RESO_960_540 = 19,
    E_BC_RESO_800_600 = 20,
    E_BC_RESO_640_360 = 21,
    E_BC_RESO_960P_SUB = 22,
    E_BC_RESO_480_270 = 23,
    E_BC_RESO_480_256 = 24,
    E_BC_RESO_320_180 = 25,
    E_BC_RESO_320_240 = 26,
    E_BC_RESO_854_480 = 27,
    E_BC_RESO_640_480 = 28,
    E_BC_RESO_640_352 = 29,
    E_BC_RESO_2560_1600 = 30,
    E_BC_RESO_1280_960 = 31,
    E_BC_RESO_2048_1536 = 32,
    E_BC_RESO_512_384 = 33,
    E_BC_RESO_2304_1296 = 34,
    E_BC_RESO_1152_648 = 35,
    E_BC_RESO_768_432 = 36,
    E_BC_RESO_2512_1520 = 37,
    E_BC_RESO_1536_1536 = 38,
    E_BC_RESO_1024_576 = 39,
    E_BC_RESO_928_512 = 40,
    E_BC_RESO_2560_1440 = 41,
    E_BC_RESO_896_512 = 42,
    E_BC_RESO_720_416 = 43,
    E_BC_RESO_1280_720_V2 = 44,
    E_BC_RESO_2560_1944 = 45,
    E_BC_RESO_960P_V2 = 46,
    E_BC_RESO_960P_V3 = 47,
    E_BC_RESO_1280_720_v3 = 48,
    E_BC_RESO_1920_1080_v2 = 49,
    E_BC_RESO_3072_2048 = 50,
    E_BC_RESO_3840_2160 = 51,
    E_BC_RESO_3072_1728 = 52,
    E_BC_RESO_2592_1944 = 53,
    E_BC_RESO_2560_1920 = 54,
    E_BC_RESO_1440_1080 = 55,
    E_BC_RESO_896_672 = 56,
    E_BC_RESO_BUTT = 57
}
export declare enum BC_ALARM_IN_E {
    E_BC_ALARM_IN_MD = 0,
    E_BC_ALARM_IN_VL = 1,
    E_BC_ALARM_IN_IO = 2,
    E_BC_ALARM_IN_BLIND = 3,
    E_BC_ALARM_IN_HDEXP = 4,
    E_BC_ALARM_IN_HDFULL = 5,
    E_BC_ALARM_IN_IPCONFLICT = 6,
    E_BC_ALARM_IN_NETCONNECT = 7,
    E_BC_ALARM_IN_RF = 8,
    E_BC_ALARM_IN_FD = 9,
    E_BC_ALARM_IN_VS = 10,
    E_BC_ALARM_IN_ID = 11,
    E_BC_ALARM_IN_RFSENSO_LOW_POWER = 12,
    E_BC_ALARM_IN_RFSENSO_TAMPER = 13,
    E_BC_ALARM_IN_DONGLE_LOST = 14,
    E_BC_ALARM_IN_BUTT = 15
}
export declare enum BC_ALARM_OUT_E {
    E_BC_ALARM_OUT_IO = 0,
    E_BC_ALARM_OUT_SNAP = 1,
    E_BC_ALARM_OUT_REC = 2,
    E_BC_ALARM_OUT_LED = 3,
    E_BC_ALARM_OUT_BUZZ = 4,
    E_BC_ALARM_OUT_PTZ = 5,
    E_BC_ALARM_OUT_FTP = 6,
    E_BC_ALARM_OUT_SCREEN = 7,
    E_BC_ALARM_OUT_RFSPEAKER = 8,
    E_BC_ALARM_OUT_PUSH = 9,
    E_BC_ALARM_OUT_AUDIO = 10,
    E_BC_ALARM_OUT_BUTT = 11
}
export declare enum BC_IP_OBTAIN_E {
    E_BC_NT_STATIC = 0,
    E_BC_NT_DHCP = 1
}
export declare enum BC_DNS_TYPE_E {
    E_BC_DT_STATIC = 0,
    E_BC_DT_AUTO = 1
}
export declare enum BC_RF_ALARM_TYPE_E {
    BC_RF_ALARM_TYPE_OUTHOME = 0,
    BC_RF_ALARM_TYPE_INHOME = 1,
    BC_RF_ALARM_TYPE_SLEEP = 2,
    BC_RF_ALARM_TYPE_BUTT = 3
}
export declare enum BC_RF_SENSITIVITY_E {
    BC_RF_SENSITIVITY_LOW = 0,
    BC_RF_SENSITIVITY_MIDDLE = 1,
    BC_RF_SENSITIVITY_HIGH = 2
}
export declare enum BC_DDNS_TYPE_E {
    E_BC_DT_SWANN = 0,
    E_BC_DT_DYNDNS = 1,
    E_BC_DT_PEATNUTS = 2,
    E_BC_DT_3322 = 3,
    E_BC_DT_NOIP = 4,
    E_BC_DT_BUTT = 5
}
export declare enum BC_ONLINE_UPDATE_TYPE_E {
    BC_ONLINE_UPDATE_NORMAL = 0,
    BC_ONLINE_UPDATE_FORCE = 1
}
export declare enum BC_WIFI_MODE_E {
    E_BC_WIFI_MODE_STATION = 0,
    E_BC_WIFI_MODE_AP = 1
}
export declare enum BC_WIFI_AUTH_MODE_E {
    E_BC_WIFI_AUTH_OPEN = 0,
    E_BC_WIFI_AUTH_SHARED = 1,
    E_BC_WIFI_AUTH_WPAPSK = 2,
    E_BC_WIFI_AUTH_WPA2PSK = 3,
    E_BC_WIFI_AUTH_DETECT = 4,
    E_BC_WIFI_AUTH_BUTT = 5
}
export declare enum BC_WIFI_ENCRYPT_TYPE_E {
    E_BC_WIFI_ENCRYPT_NONE = 0,
    E_BC_WIFI_ENCRYPT_WEP = 1,
    E_BC_WIFI_ENCRYPT_TKIP = 2,
    E_BC_WIFI_ENCRYPT_AES = 3,
    E_BC_WIFI_ENCRYPT_DETECT = 4,
    E_BC_WIFI_ENCRYPT_BUTT = 5
}
export declare enum BC_3G4G_MODE_E {
    BC_MODE_UNKNOWN = 0,
    BC_MODE_2G = 1,
    BC_MODE_3G = 2,
    BC_MODE_4G = 3
}
export declare enum BC_FTP_TRANSPORT_MODE_E {
    BC_FTP_TRANSPORT_MODE_AUTO = 0,
    BC_FTP_TRANSPORT_MODE_PORT = 1,
    BC_FTP_TRANSPORT_MODE_PASV = 2
}
export declare enum BC_ENC_TYPE_E {
    E_BC_ENC_TYPE_H264 = 0,
    E_BC_ENC_TYPE_MPEG4 = 1,
    E_BC_ENC_TYPE_MPEG2 = 2,
    E_BC_ENC_TYPE_BUTT = 3
}
export declare enum BC_ENCODER_PROFILE_E {
    BC_ENCODER_PROFILE_DEFAULT = 0,
    BC_ENCODER_PROFILE_BASE_LINE = 1,
    BC_ENCODER_PROFILE_HIGH = 2,
    BC_ENCODER_PROFILE_MAIN = 3,
    BC_ENCODER_PROFILE_BUTT = 255
}
export declare enum BC_OSD_SIZE_E {
    E_BC_OSD_SIZE_16 = 0,
    E_BC_OSD_SIZE_32 = 1,
    E_BC_OSD_SIZE_BUTT = 2
}
export declare enum BC_LANGUAGE_E {
    E_BC_LANGUAGE_CHINESE = 0,
    E_BC_LANGUAGE_ENGLISH = 1,
    E_BC_LANGUAGE_JAPANESE = 2,
    E_BC_LANGUAGE_RUSSIAN = 3,
    E_BC_LANGUAGE_ITALIAN = 4,
    E_BC_LANGUAGE_CZECH = 5,
    E_BC_LANGUAGE_ROMANIA = 6,
    E_BC_LANGUAGE_HUNGRARY = 7,
    E_BC_LANGUAGE_FRANCE = 8,
    E_BC_LANGUAGE_SPANISH = 9,
    E_BC_LANGUAGE_PORTUGAL = 10,
    E_BC_LANGUAGE_KOREAN = 11,
    E_BC_LANGUAGE_BIGCHN = 12,
    E_BC_LANGUAGE_POLISH = 13,
    E_BC_LANGUAGE_BULGARIAN = 14,
    E_BC_LANGUAGE_GERMAN = 15,
    E_BC_LANGUAGE_PERSIAN = 16,
    E_BC_LANGUAGE_THAI = 17,
    E_BC_LANGUAGE_BUTT = 18
}
export declare enum BC_CAMERA_MODE_E {
    BC_CAMERA_MODE_AUTO = 0,
    BC_CAMERA_MODE_TVI = 1,
    BC_CAMERA_MODE_AHD = 2,
    BC_CAMERA_MODE_BUTT = 255
}
export declare enum BC_PARITY_TYPE_E {
    E_BC_PT_NONE = 0,
    E_BC_PT_ODD = 1,
    E_BC_PT_EVEN = 2
}
export declare enum BC_FLOWCONTROL_TYPE_E {
    E_BC_FT_NONE = 0,
    E_BC_FT_HARD = 1,
    E_BC_FT_XON_XOFF = 2
}
export declare enum BC_DECODE_TYPE_E {
    E_BC_DT_TC_PELCO_D = 0,
    E_BC_DT_TC_PELCO_P = 1,
    E_BC_DT_TC_PELCO_C = 2
}
export declare enum BC_ANTIFLICK_TYPE_E {
    E_BC_ANTIFLICK_TYPE_UNKOWN = 0,
    E_BC_ANTIFLICK_TYPE_50HZ = 1,
    E_BC_ANTIFLICK_TYPE_60HZ = 2,
    E_BC_ANTIFLICK_TYPE_DISABLE = 3,
    E_BC_ANTIFLICK_TYPE_BUTT = 4
}
export declare enum BC_EXPOSURE_TYPE_E {
    E_BC_EXPOSURE_TYPE_AUTO = 0,
    E_BC_EXPOSURE_TYPE_LOWNOISE = 1,
    E_BC_EXPOSURE_TYPE_FRAMERATE = 2,
    E_BC_EXPOSURE_TYPE_MANUAL = 3,
    E_BC_EXPOSURE_TYPE_BUTT = 4
}
export declare enum BC_SHUTTER_AJUST_E {
    E_BC_SHUTTER_AJUST_3 = 0,
    E_BC_SHUTTER_AJUST_4 = 1,
    E_BC_SHUTTER_AJUST_5 = 2,
    E_BC_SHUTTER_AJUST_6 = 3,
    E_BC_SHUTTER_AJUST_8 = 4,
    E_BC_SHUTTER_AJUST_12 = 5,
    E_BC_SHUTTER_AJUST_15 = 6,
    E_BC_SHUTTER_AJUST_25 = 7,
    E_BC_SHUTTER_AJUST_30 = 8,
    E_BC_SHUTTER_AJUST_50 = 9,
    E_BC_SHUTTER_AJUST_60 = 10,
    E_BC_SHUTTER_AJUST_100 = 11,
    E_BC_SHUTTER_AJUST_120 = 12,
    E_BC_SHUTTER_AJUST_250 = 13,
    E_BC_SHUTTER_AJUST_500 = 14,
    E_BC_SHUTTER_AJUST_1000 = 15,
    E_BC_SHUTTER_AJUST_2000 = 16,
    E_BC_SHUTTER_AJUST_4000 = 17,
    E_BC_SHUTTER_AJUST_10000 = 18,
    E_BC_SHUTTER_AJUST_BUTT = 19
}
export declare enum BC_AWB_SCENC_MODE_E {
    E_BC_AWB_SCENC_MODE_AUTO = 0,
    E_BC_AWB_SCENC_MODE_INDOOR = 1,
    E_BC_AWB_SCENC_MODE_OUTDOOR = 2,
    E_BC_AWB_SCENC_MODE_BUTT = 3
}
export declare enum BC_DAY_NIGHT_MODE_E {
    E_BC_DAY_NIGHT_MODE_AUTO = 0,
    E_BC_DAY_NIGHT_MODE_DAY = 1,
    E_BC_DAY_NIGHT_MODE_NIGHT = 2,
    E_BC_DAY_NIGHT_MODE_BUTT = 3
}
export declare enum BC_IR_CUT_TYPE_E {
    E_BC_IR_CUT_TYPE_AUTO = 0,
    E_BC_IR_CUT_TYPE_IR = 1,
    E_BC_IR_CUT_TYPE_BUTT = 2
}
export declare enum BC_BLC_MODE_E {
    E_BC_BLC_MODE_CLOSE = 0,
    E_BC_BLC_MODE_BLC = 1,
    E_BC_BLC_MODE_DRC = 2,
    E_BC_BLC_BUTT = 3
}
export declare enum BC_ISP_NR3D_E {
    BC_NR3D_HIGH_E = 0,
    BC_NR3D_MID_E = 1,
    BC_NR3D_LOW_E = 2,
    BC_NR3D_OFF_E = 3,
    BC_NR3D_BUTT = 255
}
export declare enum BC_LED_STATE_E {
    BC_LED_AUTO = 0,
    BC_LED_CLOSE = 1,
    BC_LED_OPEN = 2,
    BC_LED_BUTT = 3
}
export declare enum BC_LIGHT_STATE_E {
    BC_LIGHT_CLOSE = 0,
    BC_LIGHT_OPEN = 1,
    BC_LIGHT_BUTT = 2
}
export declare enum BC_BATTERY_TYPE_E {
    BC_BATTERY_TYPE_DRY = 0,
    BC_BATTERY_TYPE_CHARGE = 1
}
export declare enum BC_CHARGE_STATUS_E {
    BC_CHARGE_NONE = 0,
    BC_CHARGE_CHARGING = 1,
    BC_CHARGE_COMPLETED = 2
}
export declare enum BC_ADAPTER_STATUS_E {
    BC_ADAPTER_NONE = 0,
    BC_ADAPTER_ADAPTER = 1,
    BC_ADAPTER_SOLAR_PANELS = 2
}
export declare enum BC_RING_DOWN_MODE_E {
    BC_RING_DOWN_TIMES = 0,
    BC_RING_DOWN_CONTINUOUS = 1,
    BC_RING_DOWN_SWITCH = 2,
    BC_RING_DOWN_FROM_RAM = 3,
    BC_RING_DOWN_BUTT = 255
}
export declare enum BC_AUDIO_TYPE_E {
    BC_AUDIO_TYPE_ADPCM = 0,
    BC_AUDIO_TYPE_G711 = 1
}
export declare enum BC_SOUND_TRACK_E {
    BC_SOUND_TRACK_MONO = 0,
    BC_SOUND_TRACK_STEREO = 1
}
export declare enum BC_P2P_TYPE_E {
    BC_P2P_TYPE_UNKNOW = -1,
    BC_P2P_TYPE_NONE = 0,
    BC_P2P_TYPE_IOTC = 1,
    BC_P2P_TYPE_BC = 2,
    BC_P2P_TYPE_SONG = 3
}
export declare enum BCSDK_WARNINIG_E {
    BCSDK_WARNINIG_DISK_ENOUGH = 0,
    BCSDK_WARNINIG_DISK_NOT_ENOUGH = 1,
    BCSDK_WARNINIG_NO_WRITE_PERMISSION = 2,
    BCSDK_WARNINIG_CREATE_FOLDER_FAILED = 3
}
export declare enum BCSDK_REC_EVENT_E {
    BCSDK_REC_EVENT_NEW = 0,
    BCSDK_REC_EVENT_DELETE = 1,
    BCSDK_REC_EVENT_CREATE = 2,
    BCSDK_REC_EVENT_START = 3,
    BCSDK_REC_EVENT_STOP = 4
}
export declare enum BC_REC_SCHE_TYPE_E {
    BC_REC_SCHE_TYPE_NONE = -1,
    BC_REC_SCHE_TYPE_NORMAL = 0,
    BC_REC_SCHE_TYPE_MD = 1
}
export declare enum BCSDK_RECORD_STATE_E {
    BCSDK_RECORD_STATE_CLOSED = 0,
    BCSDK_RECORD_STATE_OPENED = 1,
    BCSDK_RECORD_STATE_STARTED = 2
}
export declare enum BC_STORAGE_TYPE_E {
    BC_STORAGE_TYPE_UNKNOWN = 0,
    BC_STORAGE_TYPE_HDD = 1,
    BC_STORAGE_TYPE_SD_CARD = 2
}
export declare enum BCSDK_TALK_STATE_E {
    BCSDK_TALK_STATE_NOTREADY = 0,
    BCSDK_TALK_STATE_OPENING = 1,
    BCSDK_TALK_STATE_OPENSUCCESS = 2,
    BCSDK_TALK_STATE_OPENFAILED = 3,
    BCSDK_TALK_STATE_OPENTIMEOUT = 4,
    BCSDK_TALK_STATE_CLOSED = 5
}
