export declare namespace ERROR {
    const E_NONE: number;
    const E_UND: number;
    const E_OOM: number;
    const E_TYPE_UNKNOWN: number;
    const E_NULL_POINTER: number;
    const E_WRONG_STATE: number;
    const E_NOT_FOUND: number;
    const E_WRONG_FORMAT: number;
    const E_UNSUPPORTED: number;
    const E_OOR: number;
    const E_EOS: number;
    const E_ILLEGAL: number;
    const E_INIT_FAIL: number;
    const E_ALLOC_FAIL: number;
    const E_REPEAT: number;
    const E_BUSY: number;
    const E_NOT_READY: number;
    const E_NOT_ENOUGH: number;
    const E_LOGIN_FAIL: number;
    const E_AUTH_FAIL: number;
    const E_TASK_EXIST: number;
    const E_NETIO_FAIL: number;
    const E_CONN_FAIL: number;
    const E_SEND_FAIL: number;
    const E_RECV_FAIL: number;
    const E_INVALID: number;
    const E_OP_TIMEOUT: number;
}
